# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message,'[ci skip]') && !contains(github.event.head_commit.message,'[skip ci]')"

    # Don't let it run for more than an hour
    timeout-minutes: 60

    # Service containers to run
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Install apt packages
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
              texlive-latex-recommended texlive-xetex \
              gettext nginx gnuplot
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build and push to Docker Hub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
          image_name: ${{ github.repository_owner }}/ledgersmb-dev-github_actions
          image_tag: latest
          context: primary
          push_git_tag: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
          push_image_and_stages: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
